// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoSubmitController from "./auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import PagyInitializerController from "./pagy_initializer_controller"
application.register("pagy-initializer", PagyInitializerController)

import TasksFormController from "./tasks_form_controller"
application.register("tasks-form", TasksFormController)

import Ui__CarouselController from "./ui/carousel_controller"
application.register("ui--carousel", Ui__CarouselController)

import Ui__CheckboxController from "./ui/checkbox_controller"
application.register("ui--checkbox", Ui__CheckboxController)

import Ui__CollapsibleController from "./ui/collapsible_controller"
application.register("ui--collapsible", Ui__CollapsibleController)

import Ui__DialogController from "./ui/dialog_controller"
application.register("ui--dialog", Ui__DialogController)

import Ui__DropdownController from "./ui/dropdown_controller"
application.register("ui--dropdown", Ui__DropdownController)

import Ui__DropzoneController from "./ui/dropzone_controller"
application.register("ui--dropzone", Ui__DropzoneController)

import Ui__HoverCardController from "./ui/hover-card_controller"
application.register("ui--hover-card", Ui__HoverCardController)

import Ui__ModeController from "./ui/mode_controller"
application.register("ui--mode", Ui__ModeController)

import Ui__PopoverController from "./ui/popover_controller"
application.register("ui--popover", Ui__PopoverController)

import Ui__SheetController from "./ui/sheet_controller"
application.register("ui--sheet", Ui__SheetController)

import Ui__SwitchController from "./ui/switch_controller"
application.register("ui--switch", Ui__SwitchController)

import Ui__TabsController from "./ui/tabs_controller"
application.register("ui--tabs", Ui__TabsController)

import Ui__ToastController from "./ui/toast_controller"
application.register("ui--toast", Ui__ToastController)

import Ui__TooltipController from "./ui/tooltip_controller"
application.register("ui--tooltip", Ui__TooltipController)
