AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "app/helpers/components/**/*"
    - "app/components/**/*.rb"

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Max: 20
  Exclude:
    - "db/**/*.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
    - "config/**/*.rb"
    - "db/**/*.rb"

Layout/LineLength:
  Exclude:
    - "bin/**"
    - "db/**/*.rb"

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*.rb"
    - "bin/**"

Metrics/PerceivedComplexity:
  Exclude:
    - "bin/**"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
  Exclude:
    - "db/schema.rb"
